# Experiment 5: Data Analytics II

### Subject: DSBDA (Data Science & Big Data Analytics)

This notebook demonstrates basic **Data Analytics II** using Python,Pandas and scikit learn on an Social network ad dataset.

### Problem Statement
**Data Analytics II**,
1. Implement logistic regression using Python/R to perform classification on
Social_Network_Ads.csv dataset.

3. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset

### Dataset Used
**Social Network Ads**

Source: https://www.kaggle.com/datasets/d4rklucif3r/social-network-ads

#### Dataset Description
The Dataset used in these models tells about whether a person of certain age having certain income purchases a product or not.
We need to predict whether a targeted audience will purchase the product or not.

In [2]:
#import the libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [3]:
#load dataset 
df=pd.read_csv("Social_Network_Ads.csv")

In [4]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
df.info

<bound method DataFrame.info of      Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]>

In [6]:
df.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [7]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [9]:
X = df.iloc[:, :-1].values #Age and EstimatedSalary
y = df.iloc[:, -1].values #Purchased

In [10]:
#train and split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [11]:
#Feature Scalin
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
#Train the logistic model
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [13]:
#predictions
y_pred=classifier.predict(X_test)

In [14]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [15]:
#Confusion Matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[65  3]
 [ 8 24]]

In [16]:
#Extract TP, FP, TN, FN

TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

print("TP:", TP)
print("FP:", FP)
print("TN:", TN)
print("FN:", FN)

TP: 24
FP: 3
TN: 65
FN: 8

In [18]:
#Performance Matrics 
#Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Error Rate
error_rate = 1 - accuracy
# Precision
precision = TP / (TP + FP)
# Recall
recall = TP / (TP + FN)

In [20]:
print("Accuracy:-",accuracy)
print("Error rate:-",error_rate)
print("precision:-",precision)
print("Recall:-",recall)

Accuracy:- 0.89
Error rate:- 0.10999999999999999
precision:- 0.8888888888888888
Recall:- 0.75