# Experiment 3: Descriptive Statistics - Measures of Central Tendency and variability
### Subject: DSBDAL (Data Science & Big Data Analytics Lab)

This notebook demonstrates basic **Descriptive Statistics - Measures of Central Tendency and variability** using Python and Pandas on an open‑source dataset.

### Problem Statement
**Descriptive Statistics - Measures of Central Tendency and variability**
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step

### Dataset Used
**Adult Dataset**

**Iris Dataset** 

Source: https://www.kaggle.com/datasets/mohithsairamreddy/salary-data

Source: https://www.kaggle.com/datasets/uciml/iris

**Problem Statement**
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable

In [2]:
#Import required libraries
import numpy as np
import pandas as pd

In [3]:
#Load dataset
df=pd.read_csv("adult_data.csv")

In [4]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [6]:
df.shape

(6704, 6)

In [7]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [8]:
print("Before deletion:", df.shape)
df.dropna(inplace=True)
print("After deletion:", df.shape)

Before deletion: (6704, 6)
After deletion: (6698, 6)

In [9]:
print("Duplicate rows before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicate rows after:", df.duplicated().sum())

Duplicate rows before: 4911
Duplicate rows after: 0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1787 entries, 0 to 6631
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  1787 non-null   float64
 1   Gender               1787 non-null   object
 2   Education Level      1787 non-null   object
 3   Job Title            1787 non-null   object
 4   Years of Experience  1787 non-null   float64
 5   Salary               1787 non-null   float64
dtypes: float64(3), object(3)
memory usage: 97.7+ KB

In [11]:
df.rename(columns={'Gender':'gender','Age':'age','Education Level':'education','Job Title':'job','Years of Experience':'experience','Salary':'salary'},inplace=True)

In [12]:
df.head()

    age  gender   education                job  experience    salary
0  32.0    Male  Bachelor's  Software Engineer         5.0   90000.0
1  28.0  Female    Master's       Data Analyst         3.0   65000.0
2  45.0    Male         PhD     Senior Manager        15.0  150000.0
3  36.0  Female  Bachelor's    Sales Associate         7.0   60000.0
4  52.0    Male    Master's           Director        20.0  200000.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   income               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [13]:
#created age group using pd.cut
bins = [0,18,30,50,100]
labels = ['teen','young','adult','senior']
df['age_group'] = pd.cut(df['age'],bins=bins,labels=labels)
print(df[['age','age_group']].head())

    age age_group
0  32.0     adult
1  28.0     young
2  45.0     adult
3  36.0     adult
4  52.0    senior

In [14]:
#Apply Group by function 
grouped_by_age = df.groupby('age_group',observed=True)['salary'].agg(['mean', 'median', 'min', 'max', 'std'])
print(grouped_by_age)

                    mean    median       min       max           std
age_group
young       70306.551724   60000.0     350.0  190000.0  35770.401971
adult      132988.858349  135000.0     500.0  250000.0  41752.974130
senior     188425.108434  190000.0  121450.0  250000.0  16403.343428

In [15]:
grouped_by_gender = df.groupby('gender')['salary'].agg(['mean', 'median', 'min', 'max', 'std'])
print(grouped_by_gender)

                 mean    median      min       max           std
gender
Female  107294.798526  104851.0    500.0  220000.0  50762.741460
Male    118056.198758  120000.0    350.0  250000.0  51854.018517
Other   125819.000000  158254.0  62852.0  166109.0  46006.694680

In [16]:
grouped_by_gender_list = df.groupby('gender')['salary'].apply(list)
grouped_by_age_list = df.groupby('age_group',observed=True)['salary'].apply(list)
print(grouped_by_gender_list)
print(grouped_by_age_list)

gender
Female    [65000.0, 60000.0, 120000.0, 45000.0, 140000.0...
Male      [90000.0, 150000.0, 200000.0, 55000.0, 80000.0...
Other     [166109.0, 69032.0, 161393.0, 104127.0, 62852....
Name: salary, dtype: object
age_group
young     [65000.0, 55000.0, 45000.0, 75000.0, 40000.0, ...
adult     [90000.0, 150000.0, 60000.0, 120000.0, 80000.0...
senior    [200000.0, 180000.0, 130000.0, 170000.0, 25000...
Name: salary, dtype: object

## Experiment 3B
2.Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.

In [36]:
#import required libraries
import numpy as np
import pandas as pd

In [37]:
#load dataset
df1=pd.read_csv("Iris.csv")

In [38]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [43]:
df1['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [45]:
iris_stats = df1.groupby('Species').describe()
iris_stats

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [46]:
df1.groupby('Species').quantile([0.25, 0.5, 0.75])

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.50   25.50          5.000         3.400          1.500
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.50   75.50          5.900         2.800          4.350
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.50  125.50          6.500         3.000          5.550
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.50           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.50           1.3
                0.75           1.5
Iris-virginica  0.25           1.8
                0.50           2.0
                0.75           2.3