# Experiment 3: Descriptive Statistics - Measures of Central Tendency and variability
### Subject: DSBDAL (Data Science & Big Data Analytics Lab)

This notebook demonstrates basic **Descriptive Statistics - Measures of Central Tendency and variability** using Python and Pandas on an open‑source dataset.

### Problem Statement
**Descriptive Statistics - Measures of Central Tendency and variability**
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step

### Dataset Used
**Adult Dataset**

**Iris Dataset** 

Source: https://www.kaggle.com/datasets/mohithsairamreddy/salary-data

Source: https://www.kaggle.com/datasets/uciml/iris

**Problem Statement**
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable

In [20]:
#Import required libraries
import numpy as np
import pandas as pd

In [21]:
#Load dataset
df=pd.read_csv("adult_data.csv")

In [22]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [24]:
df.rename(columns={'Salary': 'income'}, inplace=True)

In [35]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,income
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   income               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [28]:
group_Stats=df.groupby("Age")["income"].describe()

In [31]:
group_Stats

,count,mean,std,min,25%,50%,75%,max
Age,,,,,,,,
21.0,18.0,25000.000000,0.000000,25000.0,25000.00,25000.0,25000.0,25000.0
22.0,15.0,32910.933333,11880.865333,25000.0,25000.00,25000.0,45000.0,51832.0
23.0,104.0,47192.009615,18035.442395,579.0,35000.00,50000.0,52807.0,119836.0
24.0,240.0,51052.250000,26124.985328,25000.0,25000.00,48132.5,60000.0,125000.0
25.0,284.0,63730.387324,28777.491135,550.0,35000.00,60000.0,90000.0,169159.0
26.0,393.0,65949.106870,31167.205609,26000.0,45000.00,55000.0,85000.0,135000.0
27.0,517.0,77432.729207,33012.912794,30000.0,55000.00,70000.0,80000.0,180000.0
28.0,429.0,84140.368298,40685.862170,25000.0,60000.00,70000.0,110000.0,175000.0
29.0,444.0,85764.750000,40882.104745,350.0,60000.00,75000.0,95000.0,182000.0
30.0,449.0,100903.955457,44141.603325,25000.0,65000.00,95000.0,120000.0,190000.0
31.0,364.0,114381.461538,49219.650931,500.0,70000.00,120000.0,140000.0,195000.0
32.0,351.0,120500.179487,40343.238208,40000.0,90000.00,120000.0,145000.0,195000.0
33.0,398.0,127425.266332,41148.195089,25000.0,100000.00,123520.5,148000.0,198000.0
34.0,309.0,132065.291262,38029.021237,50000.0,100000.00,140000.0,160976.0,196000.0
35.0,200.0,119365.835000,28282.573449,35000.0,95000.00,120000.0,140000.0,190000.0
36.0,281.0,134071.725979,35196.096365,35000.0,100000.00,139413.0,160000.0,185000.0
37.0,156.0,146939.461538,32923.368331,75000.0,115000.00,150000.0,170000.0,195000.0
38.0,149.0,138185.570470,30591.206601,80000.0,119000.00,136449.0,155000.0,195000.0
39.0,158.0,147282.715190,37107.978657,55000.0,120000.00,145000.0,170000.0,210000.0
40.0,92.0,149862.989130,38457.087535,60000.0,122000.00,150000.0,160000.0,215000.0
41.0,129.0,155235.565891,32816.117854,80000.0,131000.00,151315.0,185000.0,200000.0
42.0,176.0,155952.477273,23802.443693,100000.0,139571.50,170000.0,180000.0,197000.0
43.0,158.0,165409.398734,19730.539525,105000.0,150000.00,162000.0,185000.0,198000.0
44.0,126.0,160518.873016,18377.397914,110000.0,150000.00,162037.5,170000.0,220000.0
45.0,144.0,170334.291667,26086.731136,80000.0,150000.00,180000.0,185000.0,250000.0
46.0,102.0,171242.362745,16885.301897,120000.0,160000.00,180000.0,180000.0,220000.0
47.0,47.0,178750.106383,11582.239177,135000.0,170000.00,178859.0,190000.0,200000.0
48.0,98.0,192723.846939,16884.955629,140000.0,180255.25,190000.0,210000.0,219000.0
49.0,91.0,189013.582418,18146.688329,120177.0,182392.00,185000.0,195000.0,228000.0
50.0,88.0,190849.897727,18832.132979,130000.0,180000.00,190000.0,200000.0,250000.0
51.0,30.0,200356.066667,27080.013909,130000.0,190000.00,190000.0,230000.0,240000.0
52.0,29.0,187629.379310,15720.313915,161568.0,185462.00,186963.0,190596.0,250000.0
53.0,7.0,180806.571429,11812.715266,166109.0,173054.50,181714.0,188357.0,195000.0
54.0,68.0,189816.250000,8875.741981,158254.0,190000.00,192103.5,195000.0,195270.0
55.0,16.0,198482.187500,10884.112294,183020.0,190407.25,193964.0,210000.0,210000.0
56.0,11.0,196577.636364,4507.360808,195000.0,195000.00,195000.0,195000.0,210000.0
57.0,9.0,176993.777778,31698.597168,121450.0,188232.00,191790.0,195000.0,200000.0
58.0,7.0,195715.428571,4496.983539,190004.0,192502.00,195000.0,200000.0,200000.0
60.0,5.0,186132.400000,6855.522467,179180.0,179180.00,188651.0,188651.0,195000.0
61.0,2.0,200000.000000,0.000000,200000.0,200000.00,200000.0,200000.0,200000.0
62.0,5.0,200000.000000,0.000000,200000.0,200000.00,200000.0,200000.0,200000.0

In [34]:
#List of Values for Each Category
income_list = df.groupby('Age')['income'].apply(list)
income_list

Age
21.0    [25000.0, 25000.0, 25000.0, 25000.0, 25000.0, ...
22.0    [50000.0, 51832.0, 51832.0, 50000.0, 40000.0, ...
23.0    [35000.0, 95000.0, 90000.0, 90000.0, 92000.0, ...
24.0    [40000.0, 90000.0, 90000.0, 90000.0, 90000.0, ...
25.0    [35000.0, 35000.0, 30000.0, 40000.0, 100000.0,...
26.0    [45000.0, 40000.0, 35000.0, 35000.0, 40000.0, ...
27.0    [40000.0, 45000.0, 65000.0, 45000.0, 35000.0, ...
28.0    [65000.0, 45000.0, 40000.0, 40000.0, 40000.0, ...
29.0    [55000.0, 75000.0, 75000.0, 50000.0, 50000.0, ...
30.0    [50000.0, 60000.0, 55000.0, 55000.0, 50000.0, ...
31.0    [80000.0, 55000.0, 45000.0, 55000.0, 45000.0, ...
32.0    [90000.0, 75000.0, 100000.0, 90000.0, 50000.0,...
33.0    [90000.0, 90000.0, 85000.0, 65000.0, 75000.0, ...
34.0    [80000.0, 80000.0, 90000.0, 95000.0, 105000.0,...
35.0    [65000.0, 60000.0, 105000.0, 95000.0, 120000.0...
36.0    [60000.0, 60000.0, 45000.0, 95000.0, 70000.0, ...
37.0    [110000.0, 95000.0, 95000.0, 95000.0, 95000.0,...
38.0    [110000.0, 120000.0, 90000.0, 90000.0, 80000.0...
39.0    [115000.0, 65000.0, 70000.0, 65000.0, 80000.0,...
40.0    [130000.0, 60000.0, 80000.0, 80000.0, 65000.0,...
41.0    [140000.0, 130000.0, 80000.0, 100000.0, 110000...
42.0    [120000.0, 115000.0, 120000.0, 110000.0, 10000...
43.0    [140000.0, 140000.0, 105000.0, 120000.0, 14000...
44.0    [125000.0, 220000.0, 140000.0, 110000.0, 14500...
45.0    [150000.0, 180000.0, 190000.0, 110000.0, 11000...
46.0    [170000.0, 120000.0, 135000.0, 140000.0, 15000...
47.0    [190000.0, 200000.0, 180000.0, 160000.0, 16000...
48.0    [140000.0, 190000.0, 180000.0, 170000.0, 17500...
49.0    [160000.0, 150000.0, 150000.0, 180000.0, 18000...
50.0    [250000.0, 160000.0, 130000.0, 160000.0, 18000...
51.0    [180000.0, 130000.0, 170000.0, 185000.0, 19000...
52.0    [200000.0, 250000.0, 170000.0, 190000.0, 20000...
53.0    [180000.0, 195000.0, 195000.0, 166109.0, 18171...
54.0    [195000.0, 190000.0, 195000.0, 195000.0, 19000...
55.0    [190000.0, 190000.0, 210000.0, 210000.0, 21000...
56.0    [195000.0, 195000.0, 195000.0, 195000.0, 19500...
57.0    [195000.0, 195000.0, 200000.0, 121450.0, 19179...
58.0    [200000.0, 195000.0, 200000.0, 195000.0, 20000...
60.0    [195000.0, 179180.0, 188651.0, 179180.0, 18865...
61.0                                 [200000.0, 200000.0]
62.0    [200000.0, 200000.0, 200000.0, 200000.0, 20000...
Name: income, dtype: object

## Experiment 3B
2.Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.

In [36]:
#import required libraries
import numpy as np
import pandas as pd

In [37]:
#load dataset
df1=pd.read_csv("Iris.csv")

In [38]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [43]:
df1['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [45]:
iris_stats = df1.groupby('Species').describe()
iris_stats

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [46]:
df1.groupby('Species').quantile([0.25, 0.5, 0.75])

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.50   25.50          5.000         3.400          1.500
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.50   75.50          5.900         2.800          4.350
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.50  125.50          6.500         3.000          5.550
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.50           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.50           1.3
                0.75           1.5
Iris-virginica  0.25           1.8
                0.50           2.0
                0.75           2.3