**<div style='text-align: center; font-size: 48px'><u>Mini Project - 1 : Twitter Sentiment Analysis</u></div>**

### <div align="center"> Name : Shravan Santosh Shidruk , PRN : 72311412K </div>

### <div align="center"> Dataset Used : [Data Science Tweets Dataset](https://www.kaggle.com/ruchi798/data-science-tweets) </div>

---

### <div align="center"> Problem Statement </div>

Use the following dataset and classify tweets into positive and negative tweets.

Dataset Link:  
https://www.kaggle.com/ruchi798/data-science-tweets

---

### <div align="center"> Dataset Description </div>

This mini project uses the Data Science Tweets dataset obtained from Kaggle.

The dataset contains thousands of tweets related to Data Science, Data Analysis, and Data Visualization collected from Twitter between 2010 and 2021. These tweets are used for Natural Language Processing (NLP) tasks such as sentiment analysis, text classification, and opinion mining.

Since the dataset does not contain predefined sentiment labels, sentiment polarity is generated using TextBlob based on the textual content of tweets.

Source: https://www.kaggle.com/ruchi798/data-science-tweets

This dataset is suitable for sentiment analysis as it contains real-world textual data from social media platforms that can be classified into positive and negative sentiments using machine learning techniques.

---

<b> Variable Descriptions: </b>

* date: Date and time when the tweet was posted  
* username: Twitter username of the user  
* tweet: Actual textual content of the tweet  
* replies_count: Number of replies received  
* retweets_count: Number of retweets received  
* likes_count: Number of likes received  
* hashtags: Hashtags used in the tweet  
* link: URL link of the tweet  

---

### <div align="center"> Objective </div>

The objective of this mini project is to perform sentiment analysis on Twitter data and classify tweets into positive and negative categories using Natural Language Processing (NLP) and Machine Learning techniques.

---

### <div align="center"> Technologies Used </div>

* Python  
* Pandas  
* NumPy  
* NLTK  
* TextBlob  
* Scikit-learn  
* Jupyter Notebook  

---

### <div align="center"> Machine Learning Technique Used </div>

* TF-IDF Vectorization  
* Logistic Regression Classification  

---

### 1. Import all necessary libraries

In [16]:
import pandas as pd
import numpy as np
import re
import string
import nltk

from textblob import TextBlob

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

### 2. Download Stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

### 3. Load Dataset and perform Data Preprocessing

In [18]:
df = pd.read_csv('data_science.csv',low_memory=False)

In [19]:
df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1406400408545804288,1406400396264943616,2021-06-20 05:26:01 IST,2021-06-20,05:26:01,530,1113747629282930688,ballouxfrancois,Prof Francois Balloux,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1406390341176016897,1406390341176016897,2021-06-20 04:46:01 IST,2021-06-20,04:46:01,530,788898706586275840,tdatascience,Towards Data Science,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1406386311481774083,1406386311481774083,2021-06-20 04:30:00 IST,2021-06-20,04:30:00,530,19402238,sciencenews,Science News,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,1406383545153638402,1406383545153638402,2021-06-20 04:19:01 IST,2021-06-20,04:19:01,530,788898706586275840,tdatascience,Towards Data Science,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,1406358632648818689,1406358632648818689,2021-06-20 02:40:01 IST,2021-06-20,02:40:01,530,788898706586275840,tdatascience,Towards Data Science,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

In [20]:
df.shape

(241386, 36)

In [21]:
df.isnull().sum() # as we only want there is no missing values in tweet column

id                      0
conversation_id         0
created_at              0
date                    0
time                    0
timezone                0
user_id                 0
username                0
name                    0
place              241032
tweet                   0
language                0
mentions                0
urls                    0
photos                  0
replies_count           0
retweets_count          0
likes_count             0
hashtags                0
cashtags                0
link                    0
retweet                 0
quote_url          231065
video                   0
thumbnail          131048
near               241386
geo                241386
source             241386
user_rt_id         241386
user_rt            241386
retweet_id         241386
reply_to                0
retweet_date       241386
translate          241386
trans_src          241386
trans_dest         241386
dtype: int64

In [22]:
df = df[['tweet']]

In [23]:
df.head()

                                               tweet
0  What can be done?  - Never blindly trust an ab...
1  "We need a paradigm shift from model-centric t...
2  Using high-resolution satellite data and compu...
3  .@Stephenson_Data shares four steps that will ...
4  "Curricula is inherently brittle in a world wh...

### 4. Generate Sentiment Labels using TextBlob Library

In [27]:
def get_sentiment(text):

    analysis = TextBlob(str(text))

    polarity = analysis.sentiment.polarity

    if polarity > 0:
        return 1    # positive sentiment
    else:
        return 0    # negative sentiment

### 5. Apply function

In [ ]:
df['sentiment'] = df['tweet'].apply(get_sentiment) # applied on raw tweets and not the cleaned one's as cleaned one's lose the real meaning

In [29]:
df.head()

                                               tweet  sentiment
0  What can be done?  - Never blindly trust an ab...          1
1  "We need a paradigm shift from model-centric t...          0
2  Using high-resolution satellite data and compu...          0
3  .@Stephenson_Data shares four steps that will ...          1
4  "Curricula is inherently brittle in a world wh...          1

### 6. Text Cleaning - Used for Machine Learning model

In [32]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))
def clean_text(text):

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Remove hashtags
    text = re.sub(r"#\w+", "", text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Tokenization
    words = text.split()

    # Remove stopwords + stemming
    words = [
        stemmer.stem(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

### 7. Apply cleaning

In [33]:
df['cleaned_tweet'] = df['tweet'].apply(clean_text)

In [34]:
df.head()

,tweet,sentiment,cleaned_tweet
0,What can be done? - Never blindly trust an ab...,1,done never blindli trust abstract press releas...
1,"""We need a paradigm shift from model-centric t...",0,need paradigm shift modelcentr datacentr ml de...
2,Using high-resolution satellite data and compu...,0,use highresolut satellit data comput algorithm...
3,.@Stephenson_Data shares four steps that will ...,1,share four step help new data scientist deliv ...
4,"""Curricula is inherently brittle in a world wh...",1,curricula inher brittl world indemand skill ch...

### 8. Dividing columns in Features and Labels

In [35]:
X = df['cleaned_tweet']

y = df['sentiment']

### 9. Applying Train - Test Split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

### 10. Applying TF-IDF Vectorizer

In [37]:
vectorizer = TfidfVectorizer(max_features=5000)

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

### 11. Train the Logistic Regression Model

In [38]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

### 12. Predictions

In [39]:
y_pred = model.predict(X_test)

### 13. Accuracy of the Model

In [40]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8965574381705953

### 14. Classification Report

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91     25950
           1       0.92      0.85      0.88     22328

    accuracy                           0.90     48278
   macro avg       0.90      0.89      0.90     48278
weighted avg       0.90      0.90      0.90     48278

### 15. Custom Tweet Testing

In [44]:
tweet = input("Enter Tweet: ")

cleaned = clean_text(tweet)

vector_input = vectorizer.transform([cleaned])

prediction = model.predict(vector_input)

if prediction[0] == 1:
    print("Positive Tweet 😊")
else:
    print("Negative Tweet 😡")

Positive Tweet 😊

---

### <div align="center"> Observations and Conclusion </div>

### Observations:

1. The dataset contains real-world tweets related to Data Science, Data Analysis, and Data Visualization collected from Twitter.
2. Text preprocessing techniques such as lowercasing, stopword removal, punctuation removal, and stemming helped in reducing noise from textual data.
3. TF-IDF Vectorization successfully converted textual tweets into numerical feature vectors suitable for machine learning models.
4. TextBlob was used to generate sentiment polarity scores, which helped in automatically labeling tweets as positive or negative.
5. Logistic Regression performed effectively for binary sentiment classification and achieved good prediction accuracy on the dataset.
6. Tweets containing positive words such as “love”, “great”, and “amazing” were generally classified as positive, while tweets containing words such as “bad”, “terrible”, and “hate” were classified as negative.
7. Data cleaning improved model performance by reducing irrelevant and redundant textual information.

### Conclusion:

- In this mini project, sentiment analysis was successfully performed on Twitter data using Natural Language Processing (NLP) and Machine Learning techniques.

- The tweets were preprocessed and transformed into numerical representations using TF-IDF Vectorization. Sentiment labels were generated using TextBlob polarity analysis, and Logistic Regression was used to classify tweets into positive and negative categories.

- The experiment demonstrated that machine learning algorithms can effectively analyze textual social media data and predict user sentiment with good accuracy.

- Overall, sentiment analysis is a powerful NLP application that can be used in areas such as social media monitoring, customer feedback analysis, product review analysis, and opinion mining.

---